### ISSUE TITLE
BUG: Cylindrical/Polar geometries are not fully merged

### ISSUE THREAD

**Issue by neutrinoceros** [volodia99/nonos#323]
Context: some codes, like Pluto and Idefix, have the convention that "cylindrical" and "polar" geometries, while similar, differ by the of their axes (polar is (r, phi, z), cylindrical is (r, z, phi)). In practice Idefix reserves "cylindrical" geometries for 2D cases, since everything else can be done with "polar" instead.
In nonos, we've already started merging these two cases in `VTKReader` (used for Pluto and Idefix data) and `Fargo3DReader`, which have special logic to transform data that's natively "cylindrical" back to "polar". However  the`FargoADSGReader` binary reader does not seem to adhere to this convention and will output geometry flags set to `Geometry.CYLINDRICAL`, which in turns isn't covered in `Coordinates.__init__`. This means that a `GasDataSet` object loaded from FargoADSG data is fundamentally broken at the moment:
```python
from nonos.api import GasDataSet

ds = GasDataSet(200, directory="tests/data/fargo_adsg_planet/")
ds.coords.native_from_wanted("R", "phi")
```
```python-traceback
Traceback (most recent call last):
  File "/Users/clm/dev/friends/nonos/t.py", line 4, in <module>
    ds.coords.native_from_wanted("R", "phi")
  File "/Users/clm/dev/friends/nonos/nonos/api/analysis.py", line 325, in native_from_wanted
    raise RuntimeError(f"Unknown geometry {self.geometry!r}")
RuntimeError: Unknown geometry <Geometry.CYLINDRICAL: 'cylindrical'>
```

I'll try to eliminate `Geometry.CYLINDRICAL` altogether since we don't support it anywhere else.

**Comment by volodia99** [comment]
I see. TO be sure, did you mean this logic could be implemented in `FargoADSGReader` (not `VTKReader`) ?

**Comment by neutrinoceros** [comment]
no, I did mean `VTKReader`. Fargo binary readers are now complete
